### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Fizzixnerd** [vixus0/xftwidth#5]
Hey there,

I'm looking to port this code to Haskell for use in XMonad.  However, there isn't a LICENSE file here.  Would you mind releasing this under a BSD/MIT style license?  It would really help me out.

For interests sake, I'm doing this so that XMonad can have decent Dzen2 support for text on all locations of the bar.  Repo is currently [here](https://github.com/Fizzixnerd/xmonad-config) under /site-haskell/src/XMonad/Hooks/DynamicLog/Status, though it will be moving soon to it's own repo.

Thanks!
Matt

**Comment by vixus0** [comment]
Hey, I've added an MIT license. Hope that helps!
