### ISSUE TITLE
Whitespace at the beginning/end ignored

### ISSUE THREAD

**Issue by ghost** [vixus0/xftwidth#7]
Hi,
I don't know if this is intended or not: only width from the leftmost "used" pixel to the rightmost one is measured, so e.g. `xftwidth 'some font:size=9' '|'` gives 2 or 3 px although the text is wider. `xftwidth 'some font:size=9' ' '` gives 0. Is this possible to fix?

**Comment by dcx86r** [comment]
Replace `ext.width` with `ext.xOff` on line 72.

**Comment by ghost** [comment]
Thank you so much!!!

Closing this now; if anyone else needs this, they can find it now.
